// This file was generated by a script, please do not modify it. If you see any problems, please raise an issue on  https://github.com/tsaxking/webpack-template/issues

export type Accounts = {
    id: string;
    username: string;
    key: string;
    salt: string;
    firstName: string;
    lastName: string;
    email: string;
    passwordChange: string | undefined;
    picture: string | undefined;
    verified: number;
    verification: string | undefined;
    emailChange: string | undefined;
    passwordChangeDate: number | undefined;
    phoneNumber: string | undefined;
    created: number;
};

export type Members = {
    id: string;
    title: string | undefined;
    status: string | undefined;
    bio: string | undefined;
    resume: string | undefined;
    board: number;
};

export type Roles = {
    id: string;
    name: string;
    description: string | undefined;
    rank: number;
};

export type AccountRoles = {
    accountId: string;
    roleId: string;
};

export type Permissions = {
    roleId: string;
    permission: string;
    description: string | undefined;
};

export type Version = {
    major: number;
    minor: number;
    patch: number;
};

export type Sessions = {
    id: string;
    accountId: string | undefined;
    ip: string | undefined;
    userAgent: string | undefined;
    latestActivity: number | undefined;
    requests: number;
    created: number;
    prevUrl: string | undefined;
};

export type Blacklist = {
    id: string;
    ip: string;
    created: number;
    accountId: string | undefined;
    reason: string;
};

export type AccountSettings = {
    accountId: string;
    settings: string;
};

export type Select_permissions_all = undefined;

export type Select_roles_from_name = {
    name: string;
};

export type Delete_roles_delete = {
    id: string;
};

export type Update_roles_update = {
    name: string;
    description: string | undefined;
    rank: number;
    id: string;
};

export type Insert_roles_new = {
    id: string;
    name: string;
    description: string | undefined;
    rank: number;
};

export type Select_roles_from_id = {
    id: string;
};

export type Select_roles_all = undefined;

export type Delete_sessions_delete = {
    id: string;
};

export type Delete_sessions_delete_all = undefined;

export type Update_sessions_update = {
    accountId: string | undefined;
    userAgent: string | undefined;
    latestActivity: number | undefined;
    requests: number;
    ip: string | undefined;
    prevUrl: string | undefined;
    id: string;
    customData: string;
};

export type Insert_sessions_new = {
    id: string;
    accountId: string | undefined;
    userAgent: string | undefined;
    latestActivity: number | undefined;
    requests: number;
    created: number;
    ip: string | undefined;
    prevUrl: string | undefined;
    customData: string;
};

export type Select_sessions_get = {
    id: string;
};

export type Select_sessions_all = undefined;

export type Delete_member_delete = {
    id: string;
};

export type Update_member_update_title = {
    title: string | undefined;
    id: string;
};

export type Update_member_update_status = {
    id: string;
    status: string;
};

export type Update_member_update_resume = {
    id: string;
    resume: string | undefined;
};

export type Update_member_remove_from_board = {
    id: string;
};

export type Insert_member_new = {
    id: string;
    status: string;
};

export type Update_member_update_bio = {
    bio: string | undefined;
    id: string;
};

export type Update_member_add_to_board = {
    id: string;
};

export type Select_member_all = undefined;

export type Update_account_unverify = {
    id: string;
};

export type Update_account_set_verification = {
    verification: string | undefined;
    id: string;
};

export type Delete_account_delete = {
    id: string;
};

export type Select_account_unverified = undefined;

export type Update_account_change_password = {
    salt: string;
    passwordChange: string | undefined;
    id: string;
    key: string;
};

export type Insert_account_save_settings = {
    accountId: string;
    settings: string;
};

export type Select_account_from_username = {
    username: string;
};

export type Update_account_update_picture = {
    picture: string | undefined;
    id: string;
};

export type Select_account_from_verification_key = {
    verification: string | undefined;
};

export type Select_account_verified = undefined;

export type Update_account_verify = {
    id: string;
};

export type Select_account_get_settings = {
    accountId: string;
};

export type Update_account_change_email = {
    email: string;
    id: string;
};

export type Delete_account_remove_role = {
    accountId: string;
    roleId: string;
};

export type Insert_account_add_role = {
    accountId: string;
    roleId: string;
};

export type Select_account_from_email = {
    email: string;
};

export type Insert_account_new = {
    id: string;
    username: string;
    key: string;
    salt: string;
    firstName: string;
    lastName: string;
    email: string;
    verified: number;
    verification: string | undefined;
    created: number;
    phoneNumber: string | undefined;
};

export type Update_account_request_password_change = {
    passwordChange: string | undefined;
    id: string;
};

export type Select_account_from_password_change = {
    passwordChange: string | undefined;
};

export type Select_account_from_id = {
    id: string;
};

export type Select_account_all = undefined;

export type Update_account_request_email_change = {
    emailChange: string | undefined;
    id: string;
};

export type Update_account_change_username = {
    username: string;
    id: string;
};

export type Select_db_get_version = undefined;

export type Update_db_change_version = {
    major: number;
    minor: number;
    patch: number;
};

export type Insert_db_init = {
    id: string;
    username: string;
    key: string;
    salt: string;
    firstName: string;
    lastName: string;
    email: string;
    passwordChange: string | undefined;
    picture: string | undefined;
    verified: number;
    verification: string | undefined;
    emailChange: string | undefined;
    passwordChangeDate: number | undefined;
    phoneNumber: string | undefined;
    created: number;
};

export type RolePermissions = {
    roleId: string;
    permission: string;
};

export type Insert_permissions_add_to_role = {
    roleId: string;
    permission: string;
};

export type Delete_permissions_remove_from_role = {
    roleId: string;
    permission: string;
};

export type Select_blacklist_all = undefined;

export type Update_sessions_sign_in = {
    accountId: string | undefined;
    id: string;
};

export type Update_sessions_sign_out = {
    id: string;
};

export type Insert_db_change_version = {
    major: number;
    minor: number;
    patch: number;
};

export type Delete_db_delete_version = undefined;

export type Transactions = {
    id: string;
    amount: number;
    type: string;
    status: string;
    date: number;
    bucketId: string;
    description: string;
    subtypeId: string;
    taxDeductible: number;
    archived: number;
    picture: string | undefined;
    transfer: 0 | 1;
};

export type Buckets = {
    id: string;
    name: string;
    description: string;
    created: number;
    archived: number;
    type: string;
};

export type BalanceCorrection = {
    id: string;
    date: number;
    balance: number;
    bucketId: string;
};

export type Miles = {
    id: string;
    amount: number;
    date: number;
    archived: number;
    description: string;
};

export type Subscriptions = {
    id: string;
    name: string;
    startDate: number;
    endDate: number | undefined;
    interval: 'hourly' | 'daily' | 'weekly' | 'monthly' | 'yearly';
    bucketId: string;
    subtypeId: string;
    description: string;
    picture: string | undefined;
    taxDeductible: number;
    amount: number;
    archived: number;
    type: 'deposit' | 'withdrawal';
};

export type TransactionTypes = {
    id: string;
    name: string;
    dateCreated: number;
    dateModified: number;
};

export type Subtypes = {
    id: string;
    name: string;
    dateCreated: number;
    dateModified: number;
    type: string;
    typeId: string;
};

export type Select_balance_correction_all = undefined;

export type Insert_balance_correction_new = {
    id: string;
    date: number;
    balance: number;
    bucketId: string;
};

export type Update_balance_correction_update = {
    balance: number;
    date: number;
    bucketId: string;
    id: string;
};

export type Select_buckets_all = undefined;

export type Select_buckets_archived = undefined;

export type Insert_buckets_new = {
    id: string;
    description: string;
    created: number;
    type: string;
    name: string;
};

export type Update_buckets_set_archive = {
    archived: number;
    id: string;
};

export type Update_buckets_update = {
    name: string;
    description: string;
    created: number;
    type: string;
    id: string;
};

export type Select_miles_active = undefined;

export type Select_miles_archived = undefined;

export type Select_miles_from_id = {
    id: string;
};

export type Insert_miles_new = {
    id: string;
    amount: number;
    date: number;
    archived: number;
    description: string;
};

export type Update_miles_set_archive = {
    archived: number;
    id: string;
};

export type Update_miles_update = {
    date: number;
    amount: number;
    description: string;
    id: string;
};

export type Select_subscriptions_active = undefined;

export type Select_subscriptions_archived = undefined;

export type Select_subscriptions_from_bucket = {
    bucketId: string;
};

export type Select_subscriptions_from_id = {
    id: string;
};

export type Insert_subscriptions_new = {
    id: string;
    name: string;
    startDate: number;
    endDate: number | undefined;
    interval: 'hourly' | 'daily' | 'weekly' | 'monthly' | 'yearly';
    bucketId: string;
    subtypeId: string;
    description: string;
    picture: string | undefined;
    taxDeductible: number;
    amount: number;
    type: 'deposit' | 'withdrawal';
};

export type Update_subscriptions_set_archive = {
    archived: number;
    id: string;
};

export type Update_subscriptions_update = {
    name: string;
    startDate: number;
    endDate: number | undefined;
    interval: 'hourly' | 'daily' | 'weekly' | 'monthly' | 'yearly';
    bucketId: string;
    subtypeId: string;
    description: string;
    picture: string | undefined;
    taxDeductible: number;
    amount: number;
    id: string;
};

export type Select_transactions_archived = undefined;

export type Select_transactions_between = {
    bucketId: string;
};

export type Select_transactions_deposits = undefined;

export type Select_transactions_from_bucket = {
    bucketId: string;
};

export type Select_transactions_from_id = {
    id: string;
};

export type Select_transactions_from_status = {
    status: string;
};

export type Select_transactions_from_subtype = {
    subtypeId: string;
};

export type Select_transactions_from_tax_deductible = {
    taxDecuctible: undefined;
};

export type Insert_transactions_new = {
    id: string;
    amount: number;
    type: string;
    status: string;
    date: number;
    bucketId: string;
    description: string;
    subtypeId: string;
    taxDeductible: number;
    transfer: 0 | 1;
};

export type Update_transactions_set_archive = {
    archived: number;
    id: string;
};

export type Update_transactions_update_picture = {
    picture: string | undefined;
    id: string;
};

export type Update_transactions_update = {
    amount: number;
    type: string;
    status: string;
    date: number;
    bucketId: string;
    description: string;
    subtypeId: string;
    taxDeductible: number;
    id: string;
    transfer: 0 | 1;
};

export type Select_transactions_withdrawals = undefined;

export type Select_types_all_subtypes = undefined;

export type Select_types_all_types = undefined;

export type Insert_types_new_subtype = {
    id: string;
    name: string;
    dateCreated: number;
    dateModified: number;
    type: string;
    typeId: string;
};

export type Insert_types_new_type = {
    id: string;
    name: string;
    dateCreated: number;
    dateModified: number;
};

export type Select_types_subtype_from_type = {
    typeId: string;
};

export type Update_types_update_subtype = {
    name: string;
    dateCreated: number;
    dateModified: number;
    type: string;
    typeId: string;
    id: string;
};

export type Update_types_update_type = {
    name: string;
    dateCreated: number;
    dateModified: number;
    id: string;
};

export type Delete_balance_correction_delete = {
    id: string;
};

export type Select_balance_correction_from_id = {
    id: string;
};
